"use client";
import { useEffect, useRef } from "react";
import Navbar from '@/app/navbar/page';

function useScrollReveal() {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          el.style.opacity = "1";
          el.style.transform = "translateY(0)";
          obs.disconnect();
        }
      },
      { threshold: 0.12 }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return ref;
}

const FEATURES = [
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
        <polyline points="22,6 12,13 2,6" />
      </svg>
    ),
    color: "#6366f1", bg: "rgba(99,102,241,0.10)", border: "rgba(99,102,241,0.22)",
    title: "AI Email Outreach",
    desc: "Personalised emails generated by AI for each lead — regenerate instantly with different tones and CTAs.",
  },
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z" />
      </svg>
    ),
    color: "#25D366", bg: "rgba(37,211,102,0.10)", border: "rgba(37,211,102,0.22)",
    title: "WhatsApp Messaging",
    desc: "Send AI-drafted WhatsApp messages to leads with one click, directly from your browser.",
  },
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 12 19.79 19.79 0 0 1 1.61 3.43 2 2 0 0 1 3.6 1.25h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L7.91 8.84a16 16 0 0 0 6 6l.86-.86a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 21.5 16.92z" />
      </svg>
    ),
    color: "#f97316", bg: "rgba(249,115,22,0.10)", border: "rgba(249,115,22,0.22)",
    title: "AI Call Scripts",
    desc: "Auto-generate tailored call scripts for each lead. Quick-dial with a single tap.",
  },
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="5" r="2" /><circle cx="5" cy="19" r="2" /><circle cx="19" cy="19" r="2" />
        <line x1="12" y1="7" x2="5.5" y2="17.2" /><line x1="12" y1="7" x2="18.5" y2="17.2" />
      </svg>
    ),
    color: "#3b82f6", bg: "rgba(59,130,246,0.10)", border: "rgba(59,130,246,0.22)",
    title: "Visual Workflow Builder",
    desc: "Drag-and-drop pipeline canvas. Build multi-step outreach sequences and connect nodes freely.",
  },
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" /><circle cx="9" cy="7" r="4" />
        <path d="M23 21v-2a4 4 0 0 0-3-3.87" /><path d="M16 3.13a4 4 0 0 1 0 7.75" />
      </svg>
    ),
    color: "#a855f7", bg: "rgba(168,85,247,0.10)", border: "rgba(168,85,247,0.22)",
    title: "Smart Lead Management",
    desc: "Import your leads once and access them across every channel — email, WhatsApp, and call.",
  },
  {
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="22 12 18 12 15 21 9 3 6 12 2 12" />
      </svg>
    ),
    color: "#4ade80", bg: "rgba(74,222,128,0.10)", border: "rgba(74,222,128,0.22)",
    title: "Real-time Monitoring",
    desc: "Track agent activity, message delivery, and pipeline health from a live monitoring dashboard.",
  },
];

function FeatureCard({ feature, delay }: { feature: typeof FEATURES[0]; delay: number }) {
  const ref = useScrollReveal();
  return (
    <div
      ref={ref}
      style={{
        opacity: 0,
        transform: "translateY(32px)",
        transition: `opacity 0.55s ease ${delay}ms, transform 0.55s cubic-bezier(0.22,1,0.36,1) ${delay}ms`,
        background: "rgba(255,255,255,0.65)",
        backdropFilter: "blur(20px)",
        border: `1.5px solid ${feature.border}`,
        borderRadius: 20,
        padding: "28px 24px",
        boxShadow: `0 4px 24px ${feature.bg}, 0 1px 4px rgba(0,0,0,0.06)`,
      }}
    >
      <div
        style={{
          width: 52, height: 52, borderRadius: 14, marginBottom: 16,
          display: "flex", alignItems: "center", justifyContent: "center",
          background: feature.bg, color: feature.color,
          border: `1.5px solid ${feature.border}`,
        }}
      >
        {feature.icon}
      </div>
      <h3 style={{ fontSize: "1.05rem", fontWeight: 700, color: "#1e293b", marginBottom: 8 }}>{feature.title}</h3>
      <p style={{ fontSize: "0.875rem", color: "#64748b", lineHeight: 1.6 }}>{feature.desc}</p>
    </div>
  );
}

export default function Home() {
  const featuresRef = useScrollReveal();
  const aboutHeadRef = useScrollReveal();
  const aboutCardRef = useScrollReveal();

  /* ── connector line measurement ── */
  const heroRowRef = useRef<HTMLDivElement>(null);
  const badgeRef = useRef<HTMLDivElement>(null);
  const stepRef0 = useRef<HTMLDivElement>(null);
  const stepRef1 = useRef<HTMLDivElement>(null);
  const stepRef2 = useRef<HTMLDivElement>(null);
  const svgRef = useRef<SVGSVGElement>(null);

  useEffect(() => {
    const sRefs = [stepRef0, stepRef1, stepRef2];
    let rafId: number;
    function measure() {
      const row = heroRowRef.current;
      const badge = badgeRef.current;
      const svg = svgRef.current;
      if (row && badge && svg) {
        const rr = row.getBoundingClientRect();
        const br = badge.getBoundingClientRect();
        const x1 = br.right - rr.left;
        const y1 = br.top + br.height / 2 - rr.top;
        sRefs.forEach((ref, i) => {
          if (!ref.current) return;
          const ir = ref.current.getBoundingClientRect();
          const x2 = ir.left - rr.left;
          const y2 = ir.top + ir.height / 2 - rr.top;
          const cx = (x1 + x2) / 2;
          const d = `M ${x1} ${y1} C ${cx} ${y1}, ${cx} ${y2}, ${x2} ${y2}`;
          svg.getElementById(`ovl${i + 1}`)?.setAttribute("d", d);
          svg.getElementById(`ovl${i + 1}s`)?.setAttribute("d", d);
        });
      }
      rafId = requestAnimationFrame(measure);
    }
    rafId = requestAnimationFrame(measure);
    return () => cancelAnimationFrame(rafId);
  }, []);

  return (
    <div style={{ background: "#ffffff" }}>
      <Navbar />

      {/* ── Hero ── */}
      <main className="pt-32 px-6 min-h-screen flex items-start" style={{ background: "linear-gradient(180deg, #ffffff 0%, #dbeafe 55%, #93c5fd 80%, #3b82f6 100%)" }}>
        <div ref={heroRowRef} style={{ width: "100%", display: "flex", alignItems: "center", paddingLeft: 128, paddingRight: 80, paddingTop: 16, paddingBottom: 80, gap: 0, position: "relative" }}>

          {/* ── Full-width connector SVG overlay ── */}
          <style>{`
            @keyframes dashMoveConn { from { stroke-dashoffset: 40; } to { stroke-dashoffset: 0; } }
            .hcp1 { animation: dashMoveConn 1.4s linear infinite; }
            .hcp2 { animation: dashMoveConn 1.6s linear infinite; }
            .hcp3 { animation: dashMoveConn 1.5s linear infinite; }
            @keyframes portPulse {
              0%,100% { transform: translateY(-50%) scale(1);   opacity: 0.9; }
              50%      { transform: translateY(-50%) scale(1.5); opacity: 0.45; }
            }
            .badge-port {
              position: absolute; right: -10px; top: 50%;
              transform: translateY(-50%);
              width: 14px; height: 14px; border-radius: 50%;
              background: radial-gradient(circle, #a855f7 0%, rgba(99,102,241,0.3) 100%);
              box-shadow: 0 0 14px 4px rgba(168,85,247,0.7);
              animation: portPulse 2s ease-in-out infinite;
              pointer-events: none; z-index: 10;
            }
          `}</style>
          {/* Dynamic connector SVG — paths updated every frame via rAF to track the floating card */}
          <svg
            ref={svgRef}
            style={{ position: "absolute", left: 0, top: 0, width: "100%", height: "100%", overflow: "visible", pointerEvents: "none", zIndex: 10 }}
            fill="none"
          >
            <defs>
              <filter id="svgGlow">
                <feGaussianBlur stdDeviation="3" result="blur" />
                <feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge>
              </filter>
            </defs>
            {/* Email (indigo) */}
            <path id="ovl1" d="" stroke="#6366f1" strokeWidth="2.5" strokeDasharray="9 6" fill="none" className="hcp1" filter="url(#svgGlow)" opacity="0.95" />
            <path id="ovl1s" d="" stroke="#6366f1" strokeWidth="1" fill="none" opacity="0.22" />
            <circle r="6" fill="#6366f1" filter="url(#svgGlow)">
              <animateMotion dur="1.8s" begin="0s" repeatCount="indefinite"><mpath href="#ovl1" /></animateMotion>
              <animate attributeName="opacity" values="0;1;1;0" keyTimes="0;0.08;0.92;1" dur="1.8s" begin="0s" repeatCount="indefinite" />
            </circle>
            {/* WhatsApp (green) */}
            <path id="ovl2" d="" stroke="#25D366" strokeWidth="2.5" strokeDasharray="9 6" fill="none" className="hcp2" filter="url(#svgGlow)" opacity="0.95" />
            <path id="ovl2s" d="" stroke="#25D366" strokeWidth="1" fill="none" opacity="0.22" />
            <circle r="6" fill="#25D366" filter="url(#svgGlow)">
              <animateMotion dur="1.8s" begin="-0.6s" repeatCount="indefinite"><mpath href="#ovl2" /></animateMotion>
              <animate attributeName="opacity" values="0;1;1;0" keyTimes="0;0.08;0.92;1" dur="1.8s" begin="-0.6s" repeatCount="indefinite" />
            </circle>
            {/* Call (orange) */}
            <path id="ovl3" d="" stroke="#f97316" strokeWidth="2.5" strokeDasharray="9 6" fill="none" className="hcp3" filter="url(#svgGlow)" opacity="0.95" />
            <path id="ovl3s" d="" stroke="#f97316" strokeWidth="1" fill="none" opacity="0.22" />
            <circle r="6" fill="#f97316" filter="url(#svgGlow)">
              <animateMotion dur="1.8s" begin="-1.2s" repeatCount="indefinite"><mpath href="#ovl3" /></animateMotion>
              <animate attributeName="opacity" values="0;1;1;0" keyTimes="0;0.08;0.92;1" dur="1.8s" begin="-1.2s" repeatCount="indefinite" />
            </circle>
          </svg>

          {/* ── Left: copy ── */}
          <div style={{ flex: "0 0 auto", maxWidth: 520 }}>
            <h1 className="text-6xl font-bold text-slate-900 mb-8">
              Welcome to Synapt<span className="text-blue-500">IQ</span>
            </h1>
            <p className="text-3xl text-slate-600 mb-6 font-bold">
              Turn Every Lead Into A Conversation
            </p>

            <div className="mb-8">
              <style>{`
              @keyframes gradientShift {
                0%   { background-position: 0% 50%; }
                50%  { background-position: 100% 50%; }
                100% { background-position: 0% 50%; }
              }
              @keyframes neonPulse {
                0%, 100% { text-shadow: 0 0 8px #a855f7, 0 0 22px #a855f7, 0 0 45px #7c3aed; }
                50%       { text-shadow: 0 0 5px #d946ef, 0 0 18px #c026d3, 0 0 35px #a855f7; }
              }
              @keyframes glassShake {
                0%,100% { transform: translateX(0) rotate(0deg); }
                10%     { transform: translateX(-6px) rotate(-2deg); }
                20%     { transform: translateX(6px) rotate(2deg); }
                30%     { transform: translateX(-5px) rotate(-1.5deg); }
                40%     { transform: translateX(5px) rotate(1.5deg); }
                50%     { transform: translateX(-3px) rotate(-1deg); }
                60%     { transform: translateX(3px) rotate(1deg); }
                70%     { transform: translateX(-2px) rotate(-0.5deg); }
                80%     { transform: translateX(2px) rotate(0.5deg); }
                90%     { transform: translateX(-1px) rotate(0deg); }
              }
              @keyframes borderGlow {
                0%, 100% { border-color: rgba(168,85,247,0.40); }
                50%       { border-color: rgba(217,70,239,0.75); }
              }
              .glass-badge {
                display: inline-flex; align-items: center;
                padding: 10px 28px; border-radius: 999px;
                background: linear-gradient(135deg, rgba(255,255,255,0.18) 0%, rgba(168,85,247,0.14) 50%, rgba(99,102,241,0.12) 100%);
                backdrop-filter: blur(18px) saturate(1.8);
                border: 1.5px solid rgba(168,85,247,0.40);
                animation: glassShake 2.4s ease-in-out infinite, borderGlow 2.5s ease-in-out infinite;
              }
              .neon-text {
                background: linear-gradient(90deg, #e879f9, #c084fc, #a855f7, #7c3aed, #6366f1, #a855f7, #c084fc, #e879f9);
                background-size: 300% 100%;
                -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;
                animation: gradientShift 4s ease infinite, neonPulse 2.5s ease-in-out infinite;
                font-size: 1.2rem; font-weight: 700; letter-spacing: 0.06em;
                filter: drop-shadow(0 0 8px rgba(168,85,247,0.6));
              }
              @keyframes btnGlow {
                0%, 100% { box-shadow: 0 0 18px rgba(99,102,241,0.5), 0 4px 24px rgba(99,102,241,0.30); }
                50%       { box-shadow: 0 0 32px rgba(168,85,247,0.7), 0 4px 32px rgba(168,85,247,0.45); }
              }
              .get-started-btn {
                display: inline-flex; align-items: center; gap: 10px;
                padding: 16px 40px; border-radius: 999px;
                background: linear-gradient(135deg, #6366f1 0%, #a855f7 50%, #7c3aed 100%);
                color: white; font-size: 1.1rem; font-weight: 700; letter-spacing: 0.03em;
                border: none; cursor: pointer; text-decoration: none;
                animation: btnGlow 2.5s ease-in-out infinite;
                transition: transform 0.2s ease;
              }
              .get-started-btn:hover { transform: scale(1.06) translateY(-2px); }
            `}</style>
              <div ref={badgeRef} className="glass-badge" style={{ position: "relative" }}>
                <span className="neon-text">AI-Powered Outreach Platform</span>
                {/* Port dot — origin of the 3 connector lines */}
                <span className="badge-port" />
              </div>
            </div>

            <a href="/signup" className="get-started-btn">
              Get Started
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14" /><path d="m12 5 7 7-7 7" /></svg>
            </a>

            {/* scroll hint */}
            <div style={{ marginTop: 64 }}>
              <style>{`
              @keyframes bounce { 0%,100%{transform:translateY(0)}50%{transform:translateY(8px)} }
              .scroll-hint { animation: bounce 1.6s ease-in-out infinite; }
            `}</style>
              <div className="scroll-hint" style={{ display: "inline-flex", flexDirection: "column", alignItems: "center", gap: 4, color: "rgba(100,116,139,0.7)" }}>
                <span style={{ fontSize: "0.72rem", fontWeight: 600, letterSpacing: "0.1em", textTransform: "uppercase" }}>Scroll to explore</span>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9" /></svg>
              </div>
            </div>
          </div>

          {/* ── Right: floating card ── */}
          <div style={{ flex: "1 1 auto", display: "flex", justifyContent: "flex-end", alignItems: "center", position: "relative", zIndex: 2 }}>
            <style>{`
              @keyframes cardFloat {
                0%,100% { transform: translateY(0px); }
                50%      { transform: translateY(-18px); }
              }
              @keyframes cardGlow {
                0%,100% { box-shadow: 0 24px 80px rgba(59,130,246,0.22), 0 8px 32px rgba(99,102,241,0.14), inset 0 1px 0 rgba(255,255,255,0.80); }
                50%      { box-shadow: 0 32px 100px rgba(99,102,241,0.32), 0 8px 48px rgba(168,85,247,0.20), inset 0 1px 0 rgba(255,255,255,0.80); }
              }
              .hero-glass-card { animation: cardFloat 5s ease-in-out infinite, cardGlow 4s ease-in-out infinite; }
              @keyframes flowDot {
                0%   { transform: translateY(0px);  opacity: 0; }
                12%  { opacity: 1; }
                88%  { opacity: 1; }
                100% { transform: translateY(28px); opacity: 0; }
              }
              .flow-dot-0 { position: absolute; top: 0; left: -3px; width: 8px; height: 8px; border-radius: 50%; animation: flowDot 1.6s ease-in-out infinite; }
              .flow-dot-1 { position: absolute; top: 0; left: -3px; width: 8px; height: 8px; border-radius: 50%; animation: flowDot 1.6s ease-in-out infinite 0.8s; }
            `}</style>

            <div
              className="hero-glass-card"
              style={{
                position: "relative",
                zIndex: 1,
                width: 480,
                borderRadius: 32,
                background: "linear-gradient(145deg, rgba(255,255,255,0.72) 0%, rgba(219,234,254,0.60) 50%, rgba(196,181,253,0.40) 100%)",
                backdropFilter: "blur(32px) saturate(2)",
                border: "1.5px solid rgba(255,255,255,0.85)",
                padding: "48px 44px",
                display: "flex",
                flexDirection: "column",
                gap: 30,
              }}
            >
              {/* Header row */}
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <span style={{ fontSize: "0.82rem", fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "#6366f1" }}>Live Pipeline</span>
                <span style={{ display: "flex", alignItems: "center", gap: 6, fontSize: "0.82rem", fontWeight: 600, color: "#22c55e" }}>
                  <span style={{ width: 7, height: 7, borderRadius: "50%", background: "#22c55e", display: "inline-block", animation: "btnGlow 1.8s ease-in-out infinite" }} />
                  Active
                </span>
              </div>

              {/* Steps with animated flow connectors */}
              <div style={{ display: "flex", flexDirection: "column" }}>
                {[
                  { icon: "✉️", label: "Send Email", sub: "Personalised AI draft", color: "#6366f1", bg: "rgba(99,102,241,0.10)" },
                  { icon: "💬", label: "WhatsApp Follow-up", sub: "Auto-sent after 2.5d", color: "#25D366", bg: "rgba(37,211,102,0.10)" },
                  { icon: "📞", label: "Call Lead", sub: "AI script ready", color: "#f97316", bg: "rgba(249,115,22,0.10)" },
                ].map((step, i, arr) => (
                  <div key={step.label}>
                    <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
                      <div ref={[stepRef0, stepRef1, stepRef2][i]} style={{ width: 58, height: 58, borderRadius: 18, background: step.bg, border: `1.5px solid ${step.color}30`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1.6rem", flexShrink: 0 }}>
                        {step.icon}
                      </div>
                      <div style={{ flex: 1 }}>
                        <p style={{ fontSize: "1rem", fontWeight: 700, color: "#1e293b", marginBottom: 3 }}>{step.label}</p>
                        <p style={{ fontSize: "0.82rem", color: "#64748b" }}>{step.sub}</p>
                      </div>
                      <div style={{ width: 28, height: 28, borderRadius: "50%", background: `${step.color}18`, border: `1.5px solid ${step.color}40`, display: "flex", alignItems: "center", justifyContent: "center" }}>
                        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke={step.color} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
                      </div>
                    </div>
                    {i < arr.length - 1 && (
                      <div style={{ position: "relative", height: 36, marginLeft: 28 }}>
                        <div style={{ position: "absolute", left: 0, top: 0, bottom: 0, width: 2, background: `linear-gradient(180deg, ${step.color}55, ${arr[i + 1].color}55)`, borderRadius: 2 }} />
                        <div className={`flow-dot-${i}`} style={{ background: step.color, boxShadow: `0 0 8px ${step.color}` }} />
                      </div>
                    )}
                  </div>
                ))}
              </div>

              {/* Divider */}
              <div style={{ height: 1, background: "linear-gradient(90deg, transparent, rgba(99,102,241,0.25), transparent)" }} />

              {/* Stats row */}
              <div style={{ display: "flex", justifyContent: "space-between" }}>
                {[
                  { value: "94%", label: "Open rate", color: "#6366f1" },
                  { value: "3×", label: "Reply rate", color: "#a855f7" },
                  { value: "∞", label: "Leads", color: "#3b82f6" },
                ].map(s => (
                  <div key={s.label} style={{ textAlign: "center" }}>
                    <p style={{ fontSize: "1.7rem", fontWeight: 900, color: s.color, lineHeight: 1 }}>{s.value}</p>
                    <p style={{ fontSize: "0.74rem", color: "#94a3b8", fontWeight: 600, marginTop: 5, textTransform: "uppercase", letterSpacing: "0.06em" }}>{s.label}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

        </div>
      </main>

      {/* ── Features ── */}
      <section id="features" style={{ padding: "100px 80px", background: "linear-gradient(180deg, #3b82f6 0%, #dbeafe 18%, #ffffff 35%, #f3e8ff 65%, #d8b4fe 88%, #a855f7 100%)" }}>
        <div
          ref={featuresRef}
          style={{
            opacity: 0, transform: "translateY(28px)",
            transition: "opacity 0.6s ease, transform 0.6s ease",
            textAlign: "center", marginBottom: 60,
          }}
        >
          <span style={{
            display: "inline-block", marginBottom: 16, padding: "6px 20px", borderRadius: 999,
            background: "rgba(99,102,241,0.10)", border: "1px solid rgba(99,102,241,0.22)",
            fontSize: "0.75rem", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "#6366f1",
          }}>Features</span>
          <h2 style={{ fontSize: "2.8rem", fontWeight: 800, color: "#0f172a", marginBottom: 16, lineHeight: 1.2 }}>
            Everything you need to close<br />
            <span style={{ background: "linear-gradient(90deg,#6366f1,#a855f7)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>more deals, faster</span>
          </h2>
          <p style={{ fontSize: "1.05rem", color: "#64748b", maxWidth: 560, margin: "0 auto" }}>
            SynaptIQ unifies AI writing, multi-channel messaging, and workflow automation in one clean platform.
          </p>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 24, maxWidth: 1100, margin: "0 auto" }}>
          {FEATURES.map((f, i) => <FeatureCard key={f.title} feature={f} delay={i * 80} />)}
        </div>
      </section>

      {/* ── About ── */}
      <section id="about" style={{ padding: "100px 80px 120px", background: "linear-gradient(180deg, #a855f7 0%, #e9d5ff 18%, #ffffff 35%, #dbeafe 65%, #93c5fd 85%, #3b82f6 100%)" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto" }}>
          <div
            ref={aboutHeadRef}
            style={{
              opacity: 0, transform: "translateY(28px)",
              transition: "opacity 0.6s ease, transform 0.6s ease",
              textAlign: "center", marginBottom: 64,
            }}
          >
            <span style={{
              display: "inline-block", marginBottom: 16, padding: "6px 20px", borderRadius: 999,
              background: "rgba(168,85,247,0.10)", border: "1px solid rgba(168,85,247,0.22)",
              fontSize: "0.75rem", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "#a855f7",
            }}>About</span>
            <h2 style={{ fontSize: "2.8rem", fontWeight: 800, color: "#0f172a", marginBottom: 16, lineHeight: 1.2 }}>
              Built for modern<br />
              <span style={{ background: "linear-gradient(90deg,#a855f7,#6366f1)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>sales teams</span>
            </h2>
            <p style={{ fontSize: "1.05rem", color: "#64748b", maxWidth: 560, margin: "0 auto" }}>
              We believe every lead deserves a personalised touch — not a copy-pasted template.
            </p>
          </div>

          <div
            ref={aboutCardRef}
            style={{
              opacity: 0, transform: "translateY(36px)",
              transition: "opacity 0.65s ease 0.1s, transform 0.65s cubic-bezier(0.22,1,0.36,1) 0.1s",
              display: "grid", gridTemplateColumns: "1fr 1fr", gap: 32,
            }}
          >
            {/* Mission */}
            <div style={{
              background: "linear-gradient(135deg, rgba(255,255,255,0.75) 0%, rgba(224,231,255,0.60) 100%)",
              backdropFilter: "blur(20px)", borderRadius: 24, padding: "36px 32px",
              border: "1.5px solid rgba(99,102,241,0.20)",
              boxShadow: "0 8px 40px rgba(99,102,241,0.10)",
            }}>
              <div style={{ width: 48, height: 48, borderRadius: 14, background: "rgba(99,102,241,0.12)", border: "1.5px solid rgba(99,102,241,0.22)", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 20, color: "#6366f1" }}>
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2a4 4 0 0 1 4 4c0 1.95-1.4 3.58-3.25 3.93" /><path d="M8.56 13.44A4 4 0 1 0 12 18" /><path d="M12 18a4 4 0 0 0 4-4c0-1.1-.45-2.1-1.17-2.83" /><circle cx="12" cy="12" r="1.5" fill="currentColor" /></svg>
              </div>
              <h3 style={{ fontSize: "1.2rem", fontWeight: 700, color: "#1e293b", marginBottom: 12 }}>Our Mission</h3>
              <p style={{ fontSize: "0.9rem", color: "#64748b", lineHeight: 1.75 }}>
                SynaptIQ was built to give sales professionals the power of AI without the complexity. We combine intelligent automation with human-like personalisation so every lead feels like a priority.
              </p>
            </div>

            {/* Why SynaptIQ */}
            <div style={{
              background: "linear-gradient(135deg, rgba(255,255,255,0.75) 0%, rgba(243,232,255,0.60) 100%)",
              backdropFilter: "blur(20px)", borderRadius: 24, padding: "36px 32px",
              border: "1.5px solid rgba(168,85,247,0.20)",
              boxShadow: "0 8px 40px rgba(168,85,247,0.10)",
            }}>
              <div style={{ width: 48, height: 48, borderRadius: 14, background: "rgba(168,85,247,0.12)", border: "1.5px solid rgba(168,85,247,0.22)", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 20, color: "#a855f7" }}>
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" /></svg>
              </div>
              <h3 style={{ fontSize: "1.2rem", fontWeight: 700, color: "#1e293b", marginBottom: 12 }}>Why SynaptIQ</h3>
              <p style={{ fontSize: "0.9rem", color: "#64748b", lineHeight: 1.75 }}>
                Unlike generic CRMs, SynaptIQ orchestrates AI agents that think, adapt, and act — drafting emails, scripting calls, and sending WhatsApp messages so your team can focus on closing.
              </p>
            </div>

            {/* Stats row */}
            {[
              { value: "10×", label: "Faster outreach", color: "#3b82f6", bg: "rgba(59,130,246,0.08)", border: "rgba(59,130,246,0.18)" },
              { value: "3", label: "Channels in one platform", color: "#25D366", bg: "rgba(37,211,102,0.08)", border: "rgba(37,211,102,0.18)" },
              { value: "AI", label: "Generated personalisation", color: "#a855f7", bg: "rgba(168,85,247,0.08)", border: "rgba(168,85,247,0.18)" },
              { value: "∞", label: "Leads, zero extra effort", color: "#f97316", bg: "rgba(249,115,22,0.08)", border: "rgba(249,115,22,0.18)" },
            ].map(stat => (
              <div key={stat.label} style={{
                background: `linear-gradient(135deg, rgba(255,255,255,0.75) 0%, ${stat.bg} 100%)`,
                backdropFilter: "blur(16px)", borderRadius: 20, padding: "28px 24px",
                border: `1.5px solid ${stat.border}`,
                boxShadow: `0 4px 20px ${stat.bg}`,
                display: "flex", alignItems: "center", gap: 20,
              }}>
                <span style={{ fontSize: "2.4rem", fontWeight: 900, color: stat.color, lineHeight: 1 }}>{stat.value}</span>
                <span style={{ fontSize: "0.9rem", fontWeight: 600, color: "#475569" }}>{stat.label}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer style={{
        padding: "32px 80px",
        borderTop: "1px solid rgba(255,255,255,0.50)",
        background: "rgba(255,255,255,0.30)",
        backdropFilter: "blur(12px)",
        display: "flex", alignItems: "center", justifyContent: "space-between",
      }}>
        <span style={{ fontWeight: 700, fontSize: "1rem", color: "#1e293b" }}>Synapt<span style={{ color: "#3b82f6" }}>IQ</span></span>
        <span style={{ fontSize: "0.8rem", color: "#94a3b8" }}>© 2026 SynaptIQ. All rights reserved.</span>
      </footer>
    </div>
  );
}
